project:
  type: website
  output-dir: docs
  resources: 
    - "assets/css/custom.scss"
    - "assets/css/layouts.css"

website:
  title: "Dr. Phil Chodrow"
  navbar:
    title: | 
      <span class="display-name"> Dr. <b>Phil Chodrow</b>
    style: "floating"
    collapse-level: 1	
    left: 
      - research.qmd
      - text: "For Students"
        menu: 
        - teaching.qmd
        - for-students.qmd
      - mission.qmd
      - resources.qmd
      - text: "About"
        menu: 
        - text: Me
          href: journey.qmd
        - text: Jobs at SLACs
          href: job_app.qmd
        - text: What I'm Reading
          href: reading.qmd
        - text: CV
          href: https://www.philchodrow.com/CV/cv.pdf
        - blog.qmd
      - acknowledgments.qmd
    search: true 
    pinned: true
  favicon: assets/img/favicon.png
  google-analytics: "G-0PJKK3D50S"

format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    toc-title: ""
    padding-top: "2em"
    smooth-scroll: true	

  


