---
title: "Math Autobiography"
page-layout: article
toc: true
---

My first vivid memory with mathematics is a bad one. I was in 4th grade, and I was starting at a "C" on my report card. I was a Smart Kid. I was Good At Math. I Did Not Get Cs. What happened? Well, my teacher explained, I wasn't writing down any of my steps. I was trying to work out answers in my head, to skip things and get to the end faster. So, predictably, I was getting stuff wrong. 

I learned to show my work, but I never loved my math classes. I was always pretty good at them, and usually "felt smart" while I was working on problems. But I didn't really see much point, and struggled to feel interested in my classes. [In case you're wondering, I resolved in high school that I was going to grow up to be a philosopher.]{.aside}

This changed for me late in high school, when I noticed a pattern that interested me in certain sums of powers of integers. [I was looking into formulas for things like: $\sum_{i = 1}^n i = \frac{n(n-1)}{2}$. We'll learn how to prove formulas like these in this class!]{.aside} The freedom to actually explore something for myself, to discover something interesting about mathematics, changed my entire outlook. I eventually put together a science fair project about the patterns I found. By the time I got to college, I was motivated to pursue and complete a math major. Along the way, I really benefited from the opportunity to explore the math, especially in how it was applied to modeling stuff in the real world. I think my best teachers in high school and college found ways to keep me excited about that journey, and allowed me to go a bit off of the path that they might have planned for me. 

I spent some time working as a data analyst at a healthcare nonprofit. This was a pretty transformative experience for me in a lot of ways, and one of them was the interest it gave me in data and data science. When I decided it was time for me to go to grad school, I focused on programs that would allow me to explore the mathematics of data science. Once I got there, I really appreciated the control I had over which classes I took, what I spent my time thinking about, and what I got to learn. It was perfect for me! I learned the best when I could approach a new topic with motivation from my research. I want to do $X$, so I'd better learn how to use $Y$ to do it. It was great. This is a spirit that I still try to bring to my research, and in certain ways I also try to channel it in the classes I teach. 

For me, what feels good about math is the feeling of achieving something correct, powerful, and interesting. I like the results! I think a lot of mathematicians will tell you that they love the process of working through problems, puzzling it out, etc. I'm not so much like that. In the process of working on problems, I can be stressed, grouchy, frustrated, or even a little bit angry at myself for not having gotten it yet. But when I eventually do get it -- possibly after quite a while -- I feel relieved, powerful, and motivated by what I've achieved. Maybe this isn't the healthiest relationship to have to the practice of mathematics, but it's the one I have. I overall love my life and identity as an applied mathematician, even if the going is tough sometimes. 

Going back to that C on my report card in 4th grade, there was an important lesson for me in that experience, although it took me a while to fully understand it: 

> What's important in practicing mathematics isn't "being a math person:" it's being patient, doing the work, and learning from failure. **Everyone can do this.**

I bring this lesson into my teaching: I'm committed to offering learning experiences in which everyone can grow, discover, and feel powerful through the practice of mathematics. 