---
title: "Mission"
page-layout: article
toc: true
toc-depth: 4
---


#### Science is a human endeavor. 

It is performed by humans, and has consequences for other humans. Historically and into the present, scientists are disproportionately White, male, heterosexual, cisgendered, and class-privileged. Historically and into the present, scientists have created tools used to control marginalized populations, concentrate wealth in the hands of the few, and enhance the violent power of military and police forces. 

I aspire to a more just, peaceful, and equitable role for computation, mathematics, and data science.  Toward this vision, I offer the following acknowledgments and commitments. 

#### Several of my identities are over-represented and normalized in the academy. 

I am a White, heterosexual, cisgender man, and a 2nd generation academic. I promote a more diverse scientific community by amplifying the voices of minoritized scholars, decentering myself in conversations that aren't about me, and examining how my intersecting privileges can be tools for equitable progress rather than self-advancement at the expense of others. I am aware that my work as an aspiring ally is never done, and that I will need to perpetually reexamine my own positionality and my understanding of my other commitments towards justice. 

#### Many students face unjust adversity in their STEM learning journey. 

Many female, LGBTQ+, BIPOC and disabled students encounter discouragement, trauma, and institutional barriers on account of their identities. These forms of adversity manifest systemic misogyny, homophobia, racism, and ableism.  

I envision a world in which all identities experience encouragement, safety, and grace in their pursuit of STEM education. I design inclusive classrooms with vibrant learning communities, clear expectations, and intentional assessment strategies. I conduct regular evaluations and *listen to my students* in order to understand how to make my teaching more responsive to the needs of all the learners who enter my classroom. 

#### Not all "scientific progress" serves humanity. 

Many scientists create tools for surveillance, control, advertising, physical violence, financial manipulation, and misinformation spread. 

While the choices of individuals to pursue such work is understandable in our current system of incentives, the net result is that much of our collective technical expertise actively works against our collective well-being. I work towards an ethical practice of computational science by actively incorporating ethics into my classrooms. These include case studies in algorithmic harm, as well as extended projects which model the role of computation and data science in addressing climate change, cultural representation, and systemic bias. 