---
title: "What I'm Reading"
page-layout: article
toc: true
---


One of my personal goals is to read more. Some kinds of books I like to read are sci-fi and fantasy novels; U.S. and modern world history; feminism and antiracism; and, yes, the occasional book on math, network science, or computing. 

Here's what I've been reading recently. 

## Current 

- [*Elements of Mathematical Ecology*](https://bookshop.org/p/books/elements-of-mathematical-ecology-mark-kot/9122295?ean=9780521001502&next=t) by Mark Kot
- [*Braiding Sweetgrass*](https://bookshop.org/p/books/braiding-sweetgrass-robin-wall-kimmerer/16712606?ean=9781571313560) by Robin Wall Kimmerer
- [*Devotions*](https://bookshop.org/p/books/devotions-the-selected-poems-of-mary-oliver-mary-oliver/11360214?ean=9780399563263) by Mary Oliver 
- [*Stories of Your Life and Others*](https://bookshop.org/p/books/stories-of-your-life-and-others-lib-e-ted-chiang/16687839?ean=9781101972120&next=t) by Ted Chiang
- [*If You Can't Take the Heat*](https://bookshop.org/p/books/if-you-can-t-take-the-heat-tales-of-food-feminism-and-fury-geraldine-deruiter/20159297?ean=9780593444504&next=t) by Geraldine DeRuiter
- [*Inciting Joy: Essays*](https://bookshop.org/p/books/inciting-joy-essays-ross-gay/17888734?ean=9781643753959&next=t) by Ross Gay 
- [*Balance in Motion: Cultural BioMechanics Background of Aikido Formation*](https://www.amazon.com/Balance-Motion-BioMechanics-Background-Formation/dp/1960363018) by Kei Izawa
- *Into the Gloamwood* by Sarah Matthews

## 2025

### &nbsp; Nonfiction

- [*The AI Con*](https://bookshop.org/p/books/the-ai-con-how-to-fight-big-tech-s-hype-and-create-the-future-we-want-alex-hanna/914a89ac020fc825?ean=9780063418561&next=t) by Emily Bender and Alex Hanna
- [*Breath Sweeps Mind*](https://www.amazon.com/Breath-Sweeps-Mind-Meditation-2000-01-27/dp/B01N0W8QVP) by Jean Smith
- [*Abundance*](https://bookshop.org/p/books/abundance-what-progress-takes-derek-thompson/20165403?ean=9781668023488&next=t) by Ezra Klein and Derek Thompson
- [*AI Snake Oil*](https://bookshop.org/p/books/ai-snake-oil-what-artificial-intelligence-can-do-what-it-can-t-and-how-to-tell-the-difference-arvind-narayanan/21324674?ean=9780691249131&next=t) by Arvind Narayanan and Sayash Kapoor
- [*The Sabbath World*](https://bookshop.org/p/books/the-sabbath-world-glimpses-of-a-different-order-of-time-judith-shulevitz/11719697?ean=9780812971736) by Judith Shulevitz
- [*The Anxious Generation*](https://bookshop.org/p/books/the-anxious-generation-how-the-great-rewiring-of-childhood-is-causing-an-epidemic-of-mental-illness-jonathan-haidt/20144236?ean=9780593655030&next=t) by Jonathan Haidt

### &nbsp; Fiction

- [*Project Hail Mary*](https://bookshop.org/p/books/project-hail-mary-a-novel-andy-weir/00f52c9d7f2ed7f2?ean=9780593135228&next=t) by Andy Weir
- [*Cibola Burn*](https://bookshop.org/p/books/cibola-burn-james-s-a-corey/493f50639d4fdf02?ean=9780316334686&next=t) by James S. A. Corey
- [*Abaddon's Gate*](https://bookshop.org/p/books/abaddon-s-gate-special-james-s-a-corey/20081561) by James S. A. Corey
- [*Onyx Storm*](https://bookshop.org/p/books/onyx-storm-standard-edition-rebecca-yarros/f1fa0549a36d46e3?ean=9781649377159&next=t) by Rebecca Yarros
- [*Demon Copperhead*](https://bookshop.org/p/books/demon-copperhead-barbara-kingsolver/18506689) by Barbara Kingsolver
- [*Caliban's War*](https://bookshop.org/p/books/caliban-s-war-james-s-a-corey/109809?ean=9780316129060&next=t) by James S. A. Corey
- [*Leviathan Wakes*](https://bookshop.org/p/books/leviathan-wakes-james-s-a-corey/109822?ean=9780316129084&next=t) by James S. A. Corey 
- [*Translation State*](https://bookshop.org/p/books/translation-state/18928288?ean=9780316290128&next=t) by Ann Leckie
- [*Death's End*](https://bookshop.org/p/books/death-s-end-cixin-liu/17222902?ean=9780765386632&next=t) by Liu Cixin
- [*The Dark Forest*](https://bookshop.org/p/books/the-dark-forest-cixin-liu/16519058?ean=9780765386694&next=t) by Liu Cixin
- [*The Three Body Problem*](https://bookshop.org/p/books/the-three-body-problem-cixin-liu/265918?ean=9780765382030&next=t) by Liu Cixin
- [*Iron Flame*](https://bookshop.org/p/books/iron-flame-rebecca-yarros/19737341?ean=9781649374172&next=t) by Rebecca Yarros
- [*Fourth Wing*](https://bookshop.org/p/books/fourth-wing-rebecca-yarros/18796163?ean=9781649377371&next=t) by Rebecca Yarros
- [*The Sunlit Man*](https://bookshop.org/p/books/the-sunlit-man-a-cosmere-novel-brandon-sanderson/19018164?ean=9781250899712&next=t) by Brandon Sanderson
- [*Wind and Truth*](https://bookshop.org/p/books/wind-and-truth-book-five-of-the-stormlight-archive-brandon-sanderson/20984409?ean=9781250319180&next=t) by Brandon Sanderson

## 2024

### &nbsp; Nonfiction

- [*The Spirit of Tea*](https://www.goodreads.com/book/show/3386187-the-spirit-of-tea) by Frank Hadley Murphy
- [*Caste: The Origins of Our Discontents*](https://bookshop.org/p/books/caste-oprah-s-book-club-the-origins-of-our-discontents-isabel-wilkerson/15481820?ean=9780593230275) by Isabel Wilkerson
- [*Heisenberg's War*: The Secret History of the German Bomb](https://bookshop.org/p/books/heisenberg-s-war-thomas-powers/16573241?ean=9780306810114) by Thomas Powers
- [*Cooked: A Natural History of Transformation*](https://bookshop.org/p/books/cooked-a-natural-history-of-transformation-michael-pollan/586239?ean=9780143125334&next=t) by Michael Pollan
- [*How To Do Nothing: Resisting the Attention Economy*](https://bookshop.org/p/books/how-to-do-nothing-resisting-the-attention-economy-jenny-odell/8076119?ean=9781612198552) by Jenny Odell
- [*Slow Productivity*](https://bookshop.org/p/books/slow-productivity-the-lost-art-of-accomplishment-without-burnout-cal-newport/20143790?ean=9780593544853) by Cal Newport
- [*Unmasking Autism: Discovering the New Faces of Neurodiversity*](https://bookshop.org/p/books/unmasking-autism-discovering-the-new-faces-of-neurodiversity-devon-price/17622818?ean=9780593235232) by Devon Price
- [*Modeling Social Behavior*](https://bookshop.org/p/books/modeling-social-behavior-mathematical-and-agent-based-models-of-social-dynamics-and-cultural-evolution-paul-e-smaldino/19607128?ean=9780691224145) by Paul Smaldino
- [*Why Fish Don't Exist*](https://bookshop.org/p/books/life-after-life-kate-atkinson/15285989?ean=9780316176491) by Lulu Miller


### &nbsp; Fiction

- [*Rhythm of War*](https://bookshop.org/p/books/rhythm-of-war-book-four-of-the-stormlight-archive-brandon-sanderson/15876923?ean=9780765365309&next=t) by Brandon Sanderson (reread)
- [*Dawnshard*](https://bookshop.org/p/books/dawnshard-from-the-stormlight-archive-brandon-sanderson/17346416?ean=9781250850553&next=t) by Brandon Sanderson
- [*Oathbringer*](https://bookshop.org/p/books/oathbringer-book-three-of-the-stormlight-archive-brandon-sanderson/14934086?ean=9780765365293&next=t) by Brandon Sanderson (reread)
- [*Edgedancer*](https://bookshop.org/p/books/edgedancer-from-the-stormlight-archive-brandon-sanderson/9841711?ean=9781250166548&next=t) by Brandon Sanderson
- [*Words of Radiance*](https://bookshop.org/p/books/words-of-radiance-book-two-of-the-stormlight-archive-brandon-sanderson/15554287?ean=9780765365286&next=t) by Brandon Sanderson (reread)
- [*The Way of Kings*](https://bookshop.org/p/books/the-way-of-kings-book-one-of-the-stormlight-archive-brandon-sanderson/7103144?ean=9780765365279&next=t) by Brandon Sanderson (reread)
- [*The Western Wind*](https://bookshop.org/p/books/the-western-wind-samantha-harvey/12293195) by Samantha Harvey
- [*The Book Thief*](https://bookshop.org/p/books/the-book-thief-markus-zusak/15280021?ean=9780375842207) by Markus Zusak
- [*Memory and Dream*](https://bookshop.org/p/books/memory-and-dream-charles-de-lint/7252529?ean=9780765316783) by Charles de Lint
- [*Tress of the Emerald Sea*](https://bookshop.org/p/books/winter-2023-tor-title-to-be-announced-announced/19018157?ean=9781250899651) by Brandon Sanderson
- [*Provenance*](https://bookshop.org/p/books/provenance-ann-leckie/112518?ean=9780316565202) by Ann Leckie
- [*Ancillary Mercy*](https://bookshop.org/p/books/ancillary-mercy-ann-leckie/110894?ean=9780316565189) by Ann Leckie 
- [*Ancillary Sword*](https://bookshop.org/p/books/ancillary-sword-ann-leckie/110869?ean=9780316565196) by Ann Leckie
- [*Ancillary Justice*](https://bookshop.org/p/books/ancillary-justice-ann-leckie/110863?ean=9780316246620) by Ann Leckie
- [*Dune*](https://bookshop.org/p/books/dune-frank-herbert/7502701?ean=9780441172719) by Frank Herbert   
- [*In the Lives of Puppets*](https://bookshop.org/p/books/in-the-lives-of-puppets-tj-klune/18484876?ean=9781250217448) by T. J. Klune
- [*Piranesi*](https://bookshop.org/p/books/piranesi-susanna-clarke/15861178?ean=9781635577808) by Susanna Clarke
- [*Life After Life*](https://bookshop.org/p/books/life-after-life-kate-atkinson/15285989?ean=9780316176491) by Kate Atkinson
- [*The Invisible Life of Addie LaRue*](https://bookshop.org/p/books/the-invisible-life-of-addie-larue-v-e-schwab/18413009?ean=9780765387578) by V. E. Schwab 


## 2023

### &nbsp; Nonfiction

- [*Teaching to Transgress: Education as the Practice of Freedom*](https://bookshop.org/p/books/teaching-to-transgress-education-as-the-practice-of-freedom-bell-hooks/8995273?ean=9780415908085) by bell hooks
- [*Nice White Ladies: The Truth about White Supremacy, Our Role in It, and How We Can Help Dismantle It*](https://bookshop.org/p/books/nice-white-ladies-the-truth-about-white-supremacy-our-role-in-it-and-how-we-can-help-dismantle-it-jessie-daniels/16434616?ean=9781541675865) by Jessie Daniels 
- [*The Privileged Poor: How Elite Colleges Are Failing Disadvantaged Students*](https://bookshop.org/p/books/the-privileged-poor-how-elite-colleges-are-failing-disadvantaged-students-anthony-abraham-jack/14948153?ean=9780674248243) by Anthony Abraham Jack
- [*Why Are All The Black Kids Sitting Together in the Cafeteria?*](https://bookshop.org/p/books/why-are-all-the-black-kids-sitting-together-in-the-cafeteria-and-other-conversations-about-race-beverly-daniel-tatum/12401785?ean=9780465060689) by Beverly Daniel Tatum
- [*Lost Kingdom: Hawaii's Last Queen, the Sugar Kings, and Americaa's First Imperial Venture*](https://bookshop.org/p/books/lost-kingdom-hawaiia-s-last-queen-the-sugar-kings-and-americaa-s-first-imperial-venture-julia-flynn-siler/8457414?ean=9780802120700) by Julia Flynn Siler
- [*The Guarded Gate*](https://bookshop.org/p/books/the-guarded-gate-bigotry-eugenics-and-the-law-that-kept-two-generations-of-jews-italians-and-other-european-immigrants-out-of-ameri-daniel-okrent/6688666?ean=9781476798059) by Daniel Okrent
- [*Race After Technology*](https://bookshop.org/p/books/race-after-technology-abolitionist-tools-for-the-new-jim-code-ruha-benjamin/7508567?ean=9781509526406) by Ruha Benjamin
- [*Ungrading: Why Rating Students Undermines Learning (and What to Do Instead)*](https://bookshop.org/p/books/ungrading-why-rating-students-undermines-learning-and-what-to-do-instead-susan-d-blum/14432567?ean=9781949199826), edited by Susan D. Blum

### &nbsp; Fiction

- [*A Desolation Called Peace*](https://bookshop.org/books/a-desolation-called-peace-9781250186478/9781250186478) by Arkady Martine (reread)
- [*Sharks in the Time of Saviors*](https://bookshop.org/p/books/sharks-in-the-time-of-saviors-kawai-strong-washburn/15930972?ean=9781250787316) by Kawai Strong Washburn
- [*Life After Life*](https://bookshop.org/p/books/life-after-life-kate-atkinson/15285989?ean=9780316176491) by Kate Atkinson
- [*A Memory Called Empire*](https://bookshop.org/books/a-memory-called-empire/9781250186447) by Arkady Martine (reread)
- [*Parable of the Talents*](https://bookshop.org/p/books/parable-of-the-talents-octavia-e-butler/7395430?ean=9781538732199) by Octavia Butler
- [*Parable of the Sower*](https://bookshop.org/p/books/parable-of-the-sower-octavia-e-butler/19767724?ean=9781538732182) by Octavia Butler
- [*Station Eleven*](https://bookshop.org/p/books/station-eleven-emily-st-john-mandel/586327?ean=9780804172448) by Emily St. John Mandel
- [*Under the Whispering Door*](https://bookshop.org/p/books/under-the-whispering-door-tj-klune/14596712?ean=9781250217394) by T. J. Klune
- [*Everything I Never Told You*](https://bookshop.org/p/books/everything-i-never-told-you-celeste-ng/586761?ean=9780143127550) by Celeste Ng
- [*Kindred*](https://bookshop.org/p/books/kindred-octavia-e-butler/11629395?ean=9780807083697) by Octavia Butler
- [*The World We Make*](https://bookshop.org/p/books/the-world-we-make-n-k-jemisin/18790430?ean=9780316509893) by N. K. Jemisin
- [*A Gentleman in Moscow*](https://bookshop.org/p/books/a-gentleman-in-moscow-amor-towles/10206530?ean=9780143110439) by Amor Towles

## 2022

### &nbsp; Nonfiction

- [*Stamped From the Beginning: The Definitive History of Racist Ideas in America*](https://bookshop.org/books/stamped-from-the-beginning-the-definitive-history-of-racist-ideas-in-america-9781568585987/9781568585987) by Ibram X. Kendi
- [*The Silk Roads: A New History of the World*](https://bookshop.org/books/the-silk-roads-a-new-history-of-the-world/9781101912379) by Peter Frankopan
- [*Fairness and Machine Learning: Limitations and Opportunities*](https://fairmlbook.org) by Solon Barocas, Moritz Hardt, and Arvind Narayanan
- [*Hero of Two Worlds: The Marquis de Lafayette in the Age of Revolution*](https://bookshop.org/books/hero-of-two-worlds-the-marquis-de-lafayette-in-the-age-of-revolution-9781549193071/9781541730335) by Mike Duncan
- [*The 1619 Project: A New Origin Story*](https://bookshop.org/books/the-1619-project-a-new-origin-story/9780593230572) edited by Nikole Hannah-Jones

### &nbsp; Fiction


- [*The Invisible Life of Addie LaRue*](https://bookshop.org/p/books/the-invisible-life-of-addie-larue-v-e-schwab/18413009?ean=9780765387561) by V. E. Schwab 
- [*Siren Queen*](https://bookshop.org/p/books/siren-queen-nghi-vo/18750260?ean=9781250788832) by Nghi Vo
- [*Lilith's Brood*](https://bookshop.org/books/lilith-s-brood/9780446676106) by Octavia Butler
- [*Cloud Cuckoo Land*](https://bookshop.org/books/cloud-cuckoo-land-9781982168438/9781982168438) by Anthony Doerr
- [*The Sentence*](https://bookshop.org/books/the-sentence-9798200879878/9780062671127) by Louise Erdrich
- [*Fevered Star*](https://bookshop.org/books/fevered-star-volume-2/9781534437739) by Rebecca Roanhorse
- [*The House in the Cerulean Sea*](https://bookshop.org/books/the-house-in-the-cerulean-sea/9781250217318) by T.J. Klune
- [*Far Sector*](https://www.dccomics.com/graphic-novels/far-sector) by N. K. Jemisin and Jamal Campbell
- [*The Murderbot Diaries*](https://bookshop.org/books/the-murderbot-diaries-all-systems-red-artificial-condition-rogue-protocol-exit-strategy/9781250784278) by Martha Wells
- [*The Witness for the Dead*](https://bookshop.org/books/the-witness-for-the-dead/9780765387424) by Katherine Addison
- [*The Goblin Emperor*](https://bookshop.org/books/the-goblin-emperor/9780765365682) by Katherine Addison
- [*How Long 'til Black Future Month?*](https://bookshop.org/books/how-long-til-black-future-month-stories-9780316491372/9780316491372) by N. K. Jemisin

## 2021

### &nbsp; Nonfiction

- [*Calling Bullshit*](https://bookshop.org/books/calling-bullshit-the-art-of-skepticism-in-a-data-driven-world/9780525509202) by Carl Bergstrom and Jevin West
- [*Invisible Women*](https://bookshop.org/books/invisible-women-data-bias-in-a-world-designed-for-men/9781419735219) by Caroline Criado Perez
- [*Entitled: How Male Privilege Hurts Women*](https://bookshop.org/books/entitled-how-male-privilege-hurts-women/9781984826558) by Kate Manne
- [*How to be an Antiracist*](https://bookshop.org/books/how-to-be-an-antiracist/9780525509288) by Ibram X. Kendi
- [*An Indigenous People's History of the United States*](https://bookshop.org/books/an-indigenous-peoples-history-of-the-united-states/9780807057834) by Roxanne Dunbar-Ortiz
- [*Specifications Grading*](https://bookshop.org/books/specifications-grading-restoring-rigor-motivating-students-and-saving-faculty-time/9781620362426) by Linda B. Nilson
- [*Linear Algebra and Optimization for Machine Learning*](https://bookshop.org/books/linear-algebra-and-optimization-for-machine-learning-a-textbook/9783030403430) by Charu C. Aggarwal
- [*These Truths*](https://bookshop.org/books/these-truths-a-history-of-the-united-states/9780393357424) by Jill Lepore


### &nbsp; Fiction

- [*Little Fires Everywhere*](https://bookshop.org/books/little-fires-everywhere/9780735224315) by Celeste Ng
- [*The Book of Form and Emptiness*](https://bookshop.org/books/the-book-of-form-and-emptiness/9780399563645) by Ruth Ozeki
- [*Wild Seed*](https://bookshop.org/books/wild-seed/9781538751480) by Octavia Butler
- [*A Desolation Called Peace*](https://bookshop.org/books/a-desolation-called-peace-9781250186478/9781250186478) by Arkady Martine
- [*A Memory Called Empire*](https://bookshop.org/books/a-memory-called-empire/9781250186447) by Arkady Martine
- [*Future Home of the Living God*](https://bookshop.org/books/future-home-of-the-living-god/9780062694065) by Louise Erdrich
- [*Paradise*](https://bookshop.org/books/paradise-9780804169882/9780804169882) by Toni Morrison
- [*The Dreamblood Duology*](https://bookshop.org/books/the-killing-moon/9780316187282) by N. K. Jemisin (reread)
- [*The Broken Earth Trilogy*](https://bookshop.org/books/the-broken-earth-trilogy-the-fifth-season-the-obelisk-gate-the-stone-sky/9780316527194) by N. K. Jemisin (reread)
- [*The Inheritance Trilogy*](https://bookshop.org/books/the-inheritance-trilogy/9780316334006) by N. K. Jemisin (reread)
- [*Rhythm of War*](https://bookshop.org/books/rhythm-of-war-book-four-of-the-stormlight-archive/9780765326386) by Brandon Sanderson
- [*Black Sun*](https://bookshop.org/books/black-sun-1/9781534437678) by Rebecca Roanhorse
- [*Children of Blood and Bone*](https://bookshop.org/books/children-of-blood-and-bone-9781250300119/9781250170972) by Tomi Adeyemi
- [*The Starless Sea*](https://bookshop.org/books/the-starless-sea/9781101971383) by Erin Morgenstern

## 2020

### &nbsp; Nonfiction

- [*Algorithms of Oppression*](https://bookshop.org/books/algorithms-of-oppression-how-search-engines-reinforce-racism/9781479837243) by Safiya Umoja Noble
- [*Automating Inequality*](https://bookshop.org/books/automating-inequality-how-high-tech-tools-profile-police-and-punish-the-poor/9781250215789) by Virginia Eubanks
- [*Weapons of Math Destruction*](https://bookshop.org/books/weapons-of-math-destruction-how-big-data-increases-inequality-and-threatens-democracy/9780553418835) by Cathy O'Neil
- [*Washington: A Life*](https://bookshop.org/books/washington-a-life-9780143119968/9780143119968) by Ron Chernow
- [*So You Want To Talk About Race*](https://bookshop.org/books/so-you-want-to-talk-about-race/9781580058827) by Ijoema Oluo
- [*The Making of the Atomic Bomb*](https://bookshop.org/books/the-making-of-the-atomic-bomb-9781451677614/9781451677614) by Richard Rhodes (reread)
- [*Thinking, Fast and Slow*](https://bookshop.org/books/thinking-fast-and-slow/9780374533557) by Daniel Kahneman

### &nbsp; Fiction

- [*The Sympathizer*](https://bookshop.org/books/the-sympathizer-a-novel-pulitzer-prize-for-fiction/9780802124944) by Viet Thanh Nguyen
- [*The City We Became*](https://bookshop.org/books/the-city-we-became/9780316509848) by N. K. Jemisin
- [*Good Omens*](https://bookshop.org/books/good-omens-the-nice-and-accurate-prophecies-of-agnes-nutter-witch-9780060853983/9780060853983) by Neil Gaiman and Terry Pratchett (reread)
- [*The Poisonwood Bible*](https://bookshop.org/books/the-poisonwood-bible-9780060786502/9780060786502) by Barbara Kingsolver