---
title: "Student Feedback"
page-layout: article
toc: true
toc-depth: 2
---


This is a *highly curated* subset of feedback I've received from students in both official and self-designed evaluations. I've divided the feedback into broad themes. 

## Student Growth

*This class demanded a lot from us...Overall I feel so proud of what I've been able to accomplish in this class. I feel like I've grown in my abilities to describe my ideas, communicate my coding thought process, work as a member of a group, time manage, not procrastinate, and approach problems with confidence instead of doubt. Thank you Professor Chodrow, and to all the TAs and LAs who have put so much time and love into this course! I've learned so much and I'm so excited to use it!!!* <br> - PIC16A, Winter '21

*My confidence has skyrocketed since taking this class. Coming from a low income community I felt extremely behind in the STEM field when I entered UCLA, and thought that any career with coding would just be a pipedream. Once I finished...my project it made me realize that I could actually do these things, and if I work hard and continue with my coding I could do it for a living.* <br> - PIC16A, Spring '21

*I can't believe I learned so much in the span of 10 weeks!! When I was interviewing for internships I could quote some of the class assignments and people were impressed :)* <br> - PIC16A, Spring '21

*Thank you for igniting the fire in me to pursue programming. Honestly, I entered this class scared because of the lack of coding experience. But in these three months, I ended up loving programming...I feel blessed that I got the opportunity to be in your class* <br> - PIC16A, Fall '20

*...going into this class, I was extremely worried and asking myself why I'm even trying. Thankfully, basically thanks to your doing, I'm leaving this course with a sense of pride about how much I've achieved and learned despite the voice in the back of my mind telling me I can't do it...I'm proud of the progress I've made...* <br> - PIC16A, Fall '20

*I learned so much from this quarter. I feel the blogs were very helpful for me to understand the lectures and Dr. Chodrow always answers questions in a very clear way. He also makes the class super welcoming. The project is difficult but I'm really surprised that we were able to accomplish what we have. It's a unique experience.* <br> - PIC16B, Spring '21

*This class was fast-paced, but not unmangeable--it did challenge me, but in a good way.* <br> - PIC16B, Fall '21

<!-- *This quarter I feel like my coding skills faced a sharp learning curve. Not only did I learn so much, but I also enjoyed what I was doing because I was able to understand it and felt motivated to do so. I think the structure of this class helped me really stay on top of things and not fall behind too often, which was really helpful in the overall experience.* <br> - PIC16A, Winter '21 -->

## Course Environment

*What really made a difference...was your practical and empathetic approach. Actually feeling listened to as a student?? Woah!! Crazy stuff. \[In other courses\] I consistently succeeded grade wise, but was left feeling depleted and mostly uninspired, I think in part due to feeling almost ignored as a student. Now, I have refueled hope and excitement to learn and explore topics from this course in the future.* <br> - PIC16A, Winter '21

*He is so understanding and the first professor to actually get to know my name, and he did this within the span of a few weeks. He is funny, understanding, nice and genuinely resonates with his students....I would have to say he is the best professor I've ever had.* <br> - PIC16A, Fall '20

*I just want to say that both the TA and professor did an amazing job with approaching the students and making them feel comfortable in our learning environment. It made a difficult and complex class a lot less stressful.* <br> - PIC16A, Winter '21


*His instruction and the way he has set up the class clearly demonstrates his dedication to teaching. He genuinely cares about his students and is not only very approachable but also he has given me encouragement and inspired me in my learning...To me, he represents the gold standard of what a professor should strive to be.* <br> - PIC16B, Fall '21

## Learning Communities

*When I first learned that we had to work in small groups twice a week I was a little upset...I was prepared for the worst. But I have to say the discussions were some of my favorite parts of the week...I couldn't have asked for a better group. I am so grateful for these friendships I have made.* <br> - PIC16A, Winter '21

*The best thing about PIC 16A with regards to the class is my group! Discussion sections are one of the highlights of my week! We also have scheduled a time every week where we work together on the homework. It's so refreshing to have contact with new people in these crazy circumstances.* <br> - PIC16A, Fall '20

*I think I've grown to see how valuable collaborative work is. Everyone has a unique way of working through logical problems and when these different thought processes come together, it's like they merge into one new mega thought process >:)* <br> - PIC16A, Spring '21

*Discussion activities were challenging but great; my group members and I, who aren't very vocal, often physically cheered when something ran successfully.* <br> - PIC16A, Spring '21

*I have definitely improved in my ability to work collaboratively during the duration of this quarter. In discussion, I learned to speak up and provide my opinions on certain problems we were doing even when I thought I was the least qualified person in my group to provide an input. I also learned how to truly **listen** to their inputs on how and why to solve a certain problem.* <br> - PIC16A, Fall '21

*I think creating blog posts to do the homework assignments was wonderful! I've learned so much in this course not only through Professor Chodrow but also through my peers. Professor Chodrow facilitated a collaborative environment through peer feedbacks, which I loved.* <br> - PIC16B, Spring '21

*The group project was a great way for me to make new friends and work with other students.* <br> - PIC16B, Fall '21

## Mission

*I really liked that we not only learned how to code, but also about algorithmic bias and the "darker" side of the coding/data science world that is not always equitable. He truly wants us to use our skills as a force for good and personal development.* <br> - PIC16A, Fall '21

*While I am not sure exactly where I am going to end up career wise, being cognizant of the flawed relationship between algorithms and race/systemic biases will be important to my life no matter what...Right now I am able to grapple with the ideas of all these forms of bias, and I hope to notice them and do my part in dismantling them in the future.* <br> - PIC16A, Winter '21


## Miscellaneous

*Phil is 100% the best professor I've had at UCLA and honestly probably the best teacher I've ever had period. Let him do whatever he wants at UCLA. Heck, make him the department chair. He deserves it.* 
<br> - PIC16A, Fall '20 
<br> 
\[Editorial note: I'm not sure this student understood what they were wishing on me.\]

*I think this was the course in which I "grew up."* <br> - PIC16B, Spring '21

*Thanks so much for a wonderful quarter! Live Long and Prosper :)* <br> - PIC16A, Fall '20 <br>
\[Editorial note: Star Trek is a running bit throughout the lecture notes.\]

*Very S-tier.* <br> - PIC16A, Spring '21

*If I could take every math/PIC class with him, I would in a heartbeat.* <br> - PIC16A, Fall '21

